import { Inter } from "next/font/google";

import { SideNavigation } from "@globals/components/Side-Navigation";
import { TopNavigation } from "@globals/components/Top-Navigation";

import classes from "./Dashboard.module.scss";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cointrade AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${classes["body"]}`}>
        <div className={classes["dashboard_layout"]}>
          <SideNavigation />
          <div className={classes["dashboard_content"]}>
            <TopNavigation />

            <main className={classes["main_section"]}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
